// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {types} from '../models';

export function AddAccount(arg1:string,arg2:string):Promise<database.Account>;

export function AddLog(arg1:string):Promise<void>;

export function AddVideo(arg1:string):Promise<database.Video>;

export function AutoSelectCover(arg1:number):Promise<Record<string, string>>;

export function BatchDeleteScreenshots(arg1:Array<string>):Promise<number>;

export function CancelUploadTask(arg1:number):Promise<void>;

export function CleanOldScreenshots():Promise<number>;

export function CreateUploadTask(arg1:number,arg2:Array<number>,arg3:any,arg4:any):Promise<Array<database.UploadTask>>;

export function DeleteAccount(arg1:number):Promise<void>;

export function DeleteAllScreenshots():Promise<number>;

export function DeleteScreenshot(arg1:string):Promise<void>;

export function DeleteUploadTask(arg1:number):Promise<void>;

export function DeleteVideo(arg1:number):Promise<void>;

export function ExecuteTask(arg1:number):Promise<void>;

export function GenerateScheduleTimes(arg1:number):Promise<Array<string>>;

export function GetAccounts():Promise<Array<database.Account>>;

export function GetAppStatus():Promise<Record<string, any>>;

export function GetAppVersion():Promise<types.AppVersion>;

export function GetCollections(arg1:string):Promise<Array<Record<string, string>>>;

export function GetLogs(arg1:types.LogQuery):Promise<Array<types.SimpleLog>>;

export function GetPlatformScreenshotStats():Promise<Array<types.PlatformScreenshotConfig>>;

export function GetScheduleConfig():Promise<database.ScheduleConfig>;

export function GetScreenshotConfig():Promise<types.ScreenshotConfig>;

export function GetScreenshots(arg1:types.ScreenshotQuery):Promise<types.ScreenshotListResult>;

export function GetUploadTasks(arg1:string):Promise<Array<database.UploadTask>>;

export function GetVideos():Promise<Array<database.Video>>;

export function LoginAccount(arg1:number):Promise<void>;

export function OpenDirectory(arg1:string):Promise<void>;

export function OpenScreenshotDir(arg1:string):Promise<void>;

export function RetryUploadTask(arg1:number):Promise<void>;

export function SelectFile(arg1:string):Promise<string>;

export function SelectImageFile():Promise<string>;

export function SelectVideoFile():Promise<string>;

export function UpdateAccount(arg1:database.Account):Promise<void>;

export function UpdateScheduleConfig(arg1:database.ScheduleConfig):Promise<void>;

export function UpdateScreenshotConfig(arg1:types.ScreenshotConfig):Promise<void>;

export function UpdateVideo(arg1:database.Video):Promise<void>;

export function ValidateAccount(arg1:number):Promise<boolean>;

export function ValidateProductLink(arg1:string):Promise<Record<string, any>>;
