// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddAccount(arg1, arg2) {
  return window['go']['app']['App']['AddAccount'](arg1, arg2);
}

export function AddLog(arg1) {
  return window['go']['app']['App']['AddLog'](arg1);
}

export function AddVideo(arg1) {
  return window['go']['app']['App']['AddVideo'](arg1);
}

export function AutoSelectCover(arg1) {
  return window['go']['app']['App']['AutoSelectCover'](arg1);
}

export function BatchDeleteScreenshots(arg1) {
  return window['go']['app']['App']['BatchDeleteScreenshots'](arg1);
}

export function CancelUploadTask(arg1) {
  return window['go']['app']['App']['CancelUploadTask'](arg1);
}

export function CleanOldScreenshots() {
  return window['go']['app']['App']['CleanOldScreenshots']();
}

export function ClearThumbnail(arg1) {
  return window['go']['app']['App']['ClearThumbnail'](arg1);
}

export function CreateUploadTask(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['CreateUploadTask'](arg1, arg2, arg3, arg4);
}

export function DeleteAccount(arg1) {
  return window['go']['app']['App']['DeleteAccount'](arg1);
}

export function DeleteAllScreenshots() {
  return window['go']['app']['App']['DeleteAllScreenshots']();
}

export function DeleteScreenshot(arg1) {
  return window['go']['app']['App']['DeleteScreenshot'](arg1);
}

export function DeleteUploadTask(arg1) {
  return window['go']['app']['App']['DeleteUploadTask'](arg1);
}

export function DeleteVideo(arg1) {
  return window['go']['app']['App']['DeleteVideo'](arg1);
}

export function ExecuteTask(arg1) {
  return window['go']['app']['App']['ExecuteTask'](arg1);
}

export function ExtractVideoFrame(arg1, arg2) {
  return window['go']['app']['App']['ExtractVideoFrame'](arg1, arg2);
}

export function GenerateScheduleTimes(arg1) {
  return window['go']['app']['App']['GenerateScheduleTimes'](arg1);
}

export function GetAccounts() {
  return window['go']['app']['App']['GetAccounts']();
}

export function GetAppStatus() {
  return window['go']['app']['App']['GetAppStatus']();
}

export function GetAppVersion() {
  return window['go']['app']['App']['GetAppVersion']();
}

export function GetBrowserPoolConfig() {
  return window['go']['app']['App']['GetBrowserPoolConfig']();
}

export function GetCollections(arg1) {
  return window['go']['app']['App']['GetCollections'](arg1);
}

export function GetHeadlessConfig() {
  return window['go']['app']['App']['GetHeadlessConfig']();
}

export function GetLogPlatforms() {
  return window['go']['app']['App']['GetLogPlatforms']();
}

export function GetLogs(arg1) {
  return window['go']['app']['App']['GetLogs'](arg1);
}

export function GetPlatformScreenshotStats() {
  return window['go']['app']['App']['GetPlatformScreenshotStats']();
}

export function GetScheduleConfig() {
  return window['go']['app']['App']['GetScheduleConfig']();
}

export function GetScreenshotConfig() {
  return window['go']['app']['App']['GetScreenshotConfig']();
}

export function GetScreenshots(arg1) {
  return window['go']['app']['App']['GetScreenshots'](arg1);
}

export function GetUploadTasks(arg1) {
  return window['go']['app']['App']['GetUploadTasks'](arg1);
}

export function GetVideos() {
  return window['go']['app']['App']['GetVideos']();
}

export function IsLogDedupEnabled() {
  return window['go']['app']['App']['IsLogDedupEnabled']();
}

export function LoginAccount(arg1) {
  return window['go']['app']['App']['LoginAccount'](arg1);
}

export function OpenDirectory(arg1) {
  return window['go']['app']['App']['OpenDirectory'](arg1);
}

export function OpenScreenshotDir(arg1) {
  return window['go']['app']['App']['OpenScreenshotDir'](arg1);
}

export function ReloginAccount(arg1) {
  return window['go']['app']['App']['ReloginAccount'](arg1);
}

export function RetryUploadTask(arg1) {
  return window['go']['app']['App']['RetryUploadTask'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['app']['App']['SelectFile'](arg1);
}

export function SelectImageFile() {
  return window['go']['app']['App']['SelectImageFile']();
}

export function SelectVideoFile() {
  return window['go']['app']['App']['SelectVideoFile']();
}

export function SetBrowserPoolConfig(arg1) {
  return window['go']['app']['App']['SetBrowserPoolConfig'](arg1);
}

export function SetHeadlessConfig(arg1) {
  return window['go']['app']['App']['SetHeadlessConfig'](arg1);
}

export function SetLogDedupEnabled(arg1) {
  return window['go']['app']['App']['SetLogDedupEnabled'](arg1);
}

export function UpdateAccount(arg1) {
  return window['go']['app']['App']['UpdateAccount'](arg1);
}

export function UpdateScheduleConfig(arg1) {
  return window['go']['app']['App']['UpdateScheduleConfig'](arg1);
}

export function UpdateScreenshotConfig(arg1) {
  return window['go']['app']['App']['UpdateScreenshotConfig'](arg1);
}

export function UpdateVideo(arg1) {
  return window['go']['app']['App']['UpdateVideo'](arg1);
}

export function UploadThumbnail(arg1, arg2) {
  return window['go']['app']['App']['UploadThumbnail'](arg1, arg2);
}

export function ValidateAccount(arg1) {
  return window['go']['app']['App']['ValidateAccount'](arg1);
}

export function ValidateProductLink(arg1) {
  return window['go']['app']['App']['ValidateProductLink'](arg1);
}
